/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as WorkflowsIndexImport } from './routes/workflows/index'
import { Route as RepositoriesIndexImport } from './routes/repositories/index'
import { Route as WorkflowsWorkflowIdImport } from './routes/workflows/$workflowId'
import { Route as RepositoriesRepoIdImport } from './routes/repositories/$repoId'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WorkflowsIndexRoute = WorkflowsIndexImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => rootRoute,
} as any)

const RepositoriesIndexRoute = RepositoriesIndexImport.update({
  id: '/repositories/',
  path: '/repositories/',
  getParentRoute: () => rootRoute,
} as any)

const WorkflowsWorkflowIdRoute = WorkflowsWorkflowIdImport.update({
  id: '/workflows/$workflowId',
  path: '/workflows/$workflowId',
  getParentRoute: () => rootRoute,
} as any)

const RepositoriesRepoIdRoute = RepositoriesRepoIdImport.update({
  id: '/repositories/$repoId',
  path: '/repositories/$repoId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/repositories/$repoId': {
      id: '/repositories/$repoId'
      path: '/repositories/$repoId'
      fullPath: '/repositories/$repoId'
      preLoaderRoute: typeof RepositoriesRepoIdImport
      parentRoute: typeof rootRoute
    }
    '/workflows/$workflowId': {
      id: '/workflows/$workflowId'
      path: '/workflows/$workflowId'
      fullPath: '/workflows/$workflowId'
      preLoaderRoute: typeof WorkflowsWorkflowIdImport
      parentRoute: typeof rootRoute
    }
    '/repositories/': {
      id: '/repositories/'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesIndexImport
      parentRoute: typeof rootRoute
    }
    '/workflows/': {
      id: '/workflows/'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof WorkflowsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/repositories': typeof RepositoriesIndexRoute
  '/workflows': typeof WorkflowsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/repositories/$repoId': typeof RepositoriesRepoIdRoute
  '/workflows/$workflowId': typeof WorkflowsWorkflowIdRoute
  '/repositories/': typeof RepositoriesIndexRoute
  '/workflows/': typeof WorkflowsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/repositories/$repoId'
    | '/workflows/$workflowId'
    | '/repositories'
    | '/workflows'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/repositories/$repoId'
    | '/workflows/$workflowId'
    | '/repositories'
    | '/workflows'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/repositories/$repoId'
    | '/workflows/$workflowId'
    | '/repositories/'
    | '/workflows/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  RepositoriesRepoIdRoute: typeof RepositoriesRepoIdRoute
  WorkflowsWorkflowIdRoute: typeof WorkflowsWorkflowIdRoute
  RepositoriesIndexRoute: typeof RepositoriesIndexRoute
  WorkflowsIndexRoute: typeof WorkflowsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  RepositoriesRepoIdRoute: RepositoriesRepoIdRoute,
  WorkflowsWorkflowIdRoute: WorkflowsWorkflowIdRoute,
  RepositoriesIndexRoute: RepositoriesIndexRoute,
  WorkflowsIndexRoute: WorkflowsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/repositories/$repoId",
        "/workflows/$workflowId",
        "/repositories/",
        "/workflows/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/repositories/$repoId": {
      "filePath": "repositories/$repoId.tsx"
    },
    "/workflows/$workflowId": {
      "filePath": "workflows/$workflowId.tsx"
    },
    "/repositories/": {
      "filePath": "repositories/index.tsx"
    },
    "/workflows/": {
      "filePath": "workflows/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
